services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt-lib:/var/lib/letsencrypt
    entrypoint: >
      certbot certonly
      --standalone
      --agree-tos
      --non-interactive
      -m ${ACME_MAIL}
      -d ${DOMAIN}
    networks:
      - web-net
    restart: no

  nginx:
    image: nginx:1.27.2-alpine3.20
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - web-net
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
      - ./letsencrypt:/etc/letsencrypt:ro
    healthcheck:
      test: ["CMD", "curl", "-k", "https://127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      certbot:
        condition: service_completed_successfully
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '1.0'
          memory: 256M

networks:
  web-net:
